// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Std               = require("bs-sentia-std/lib/js/src/Std.js");
var Js_primitive      = require("bs-platform/lib/js/js_primitive.js");
var Http$BsSentiaHttp = require("../src/http.js");

function onError(e) {
  if (typeof e === "number") {
    if (e !== 0) {
      console.log("NetworkError");
      return /* () */0;
    } else {
      console.log("Timeout");
      return /* () */0;
    }
  } else {
    console.log("BadResponse", e[0], e[1]);
    return /* () */0;
  }
}

function onSuccess(d) {
  console.log(d);
  return /* () */0;
}

var query = "\n  {\n    authenticate(email: \"andreas@sentia.io\", password: \"password\") {\n      token\n    }\n  }\n";

var payload = {
  query: query,
  variables: {
    session: ""
  }
};

var body = Std.Option[/* withDefault */7]("", Js_primitive.undefined_to_opt(JSON.stringify(payload)));

Std.Task[/* fork */11](onError, onSuccess, Http$BsSentiaHttp.post(/* None */0, body, "https://gain.ai:8090/graphql"));

exports.onError   = onError;
exports.onSuccess = onSuccess;
exports.query     = query;
exports.payload   = payload;
exports.body      = body;
/* body Not a pure module */
