// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Http = require("../src/http.js");

function callback(res) {
  if (res.tag) {
    var e = res[0];
    if (typeof e === "number") {
      if (e !== 0) {
        console.log("NetworkError");
        return /* () */0;
      } else {
        console.log("Timeout");
        return /* () */0;
      }
    } else {
      var match = e[0];
      console.log("BadResponse", match[/* status */0], match[/* body */3]);
      return /* () */0;
    }
  } else {
    console.log(res[0]);
    return /* () */0;
  }
}

var query = "\n  {\n    authenticate(email: \"andreas@sentia.io\", password: \"password\") {\n      token\n    }\n  }\n";

var payload = {
  query: query,
  variables: {
    session: ""
  }
};

var match = JSON.stringify(payload);

var body = match !== undefined ? match : "";

Http.post(/* None */0, body, "https://gain.ai:8090/graphql")(callback);

exports.callback = callback;
exports.query = query;
exports.payload = payload;
exports.body = body;
/* match Not a pure module */
